package interfaces;



import com.mysql.jdbc.Connection;
import java.io.Serializable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import coneccion.Conexion;


/**
 *
 * @author danna
 */
public class MenuAdmin extends javax.swing.JFrame implements Serializable{
Connection cn;
private int id;
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() throws SQLException, ClassNotFoundException {
        initComponents();
        setLocationRelativeTo(null);//Centrar Ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_libros = new javax.swing.JPanel();
        btn_Menu_IngresarLibro = new javax.swing.JButton();
        btn_buscarLibro = new javax.swing.JButton();
        btn_editarLibro = new javax.swing.JButton();
        btn_eliminarLibro = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_cs = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Panel_usuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_salir2 = new javax.swing.JButton();
        btn_cs1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_ingresarEst = new javax.swing.JButton();
        btn_buscarEstudiante = new javax.swing.JButton();
        btn_editarEstudiante = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_sing_Admin = new javax.swing.JButton();
        tbn_buscarAdmin = new javax.swing.JButton();
        btn_editarAdmin = new javax.swing.JButton();
        btn_eliminarAdmin = new javax.swing.JButton();
        btn_salir3 = new javax.swing.JButton();
        btn_cs2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        panel_libros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Menu_IngresarLibro.setText("INGRESAR LIBRO");
        btn_Menu_IngresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Menu_IngresarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_Menu_IngresarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 254, -1));

        btn_buscarLibro.setText("BUSCAR LIBRO");
        btn_buscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_buscarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 254, -1));

        btn_editarLibro.setText("EDITAR LIBRO");
        btn_editarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_editarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 254, -1));

        btn_eliminarLibro.setText("ELIMINAR LIBRO");
        btn_eliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_eliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 254, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("PANEL DE ADMINISTRACION");
        panel_libros.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_libros.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 408, 125, -1));

        btn_cs.setText("CERRAR SESION");
        btn_cs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_csActionPerformed(evt);
            }
        });
        panel_libros.add(btn_cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 408, 145, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/image3.jpg"))); // NOI18N
        panel_libros.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 570));

        jTabbedPane1.addTab("Libros", panel_libros);

        Panel_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PANEL DE ADMINISTRACION");
        Panel_usuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, 27));

        btn_salir2.setText("SALIR");
        btn_salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir2ActionPerformed(evt);
            }
        });
        Panel_usuarios.add(btn_salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 510, 131, -1));

        btn_cs1.setText("CERRAR SESION");
        btn_cs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cs1ActionPerformed(evt);
            }
        });
        Panel_usuarios.add(btn_cs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 510, 145, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("AJUSTES ESTUDIANTES");
        Panel_usuarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        btn_ingresarEst.setForeground(new java.awt.Color(0, 0, 0));
        btn_ingresarEst.setText("INGRESAR ESTUDIANTE");
        btn_ingresarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarEstActionPerformed(evt);
            }
        });
        Panel_usuarios.add(btn_ingresarEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 230, -1));

        btn_buscarEstudiante.setText("BUSCAR ESTUDIANTE");
        btn_buscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarEstudianteActionPerformed(evt);
            }
        });
        Panel_usuarios.add(btn_buscarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 230, -1));

        btn_editarEstudiante.setText("EDITAR ESTUDIANTE");
        btn_editarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarEstudianteActionPerformed(evt);
            }
        });
        Panel_usuarios.add(btn_editarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 230, -1));

        jButton13.setText("ELIMINAR  ESTUDIANTE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Panel_usuarios.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 230, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/image3.jpg"))); // NOI18N
        Panel_usuarios.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 570));

        jTabbedPane1.addTab("Estudiantes", Panel_usuarios);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PANEL DE ADMINISTRACION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 27));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("AJUSTES ADMINISTRADOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        btn_sing_Admin.setForeground(new java.awt.Color(0, 0, 0));
        btn_sing_Admin.setText("INGRESAR ADMINISTRADOR");
        btn_sing_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sing_AdminActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sing_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 230, -1));

        tbn_buscarAdmin.setText("BUSCAR ADMINISTRADOR");
        tbn_buscarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_buscarAdminActionPerformed(evt);
            }
        });
        jPanel1.add(tbn_buscarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 230, -1));

        btn_editarAdmin.setText("EDITAR ADMINISTRADOR");
        btn_editarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 230, -1));

        btn_eliminarAdmin.setText("ELIMINAR ADMINISTRADOR");
        btn_eliminarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 230, -1));

        btn_salir3.setText("SALIR");
        btn_salir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 131, -1));

        btn_cs2.setText("CERRAR SESION");
        btn_cs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cs2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 145, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/image3.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 570));

        jTabbedPane1.addTab("Administradores", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cs1ActionPerformed
        this.setVisible(false);
        Login lo = new Login();
        lo.setVisible(true);
    }//GEN-LAST:event_btn_cs1ActionPerformed

    private void btn_salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salir2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            EliminarEstudiante ee = new EliminarEstudiante();
            ee.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btn_editarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarEstudianteActionPerformed
        try {
            EditarEstudiante es = new EditarEstudiante();
            es.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editarEstudianteActionPerformed

    private void btn_buscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarEstudianteActionPerformed
        try {
            BuscarEstudiante be = new BuscarEstudiante();
            be.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buscarEstudianteActionPerformed

    private void btn_ingresarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarEstActionPerformed
        IngresarEstudiante is = new IngresarEstudiante();
        is.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingresarEstActionPerformed

    private void btn_csActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_csActionPerformed
        this.setVisible(false);
        Login lo = new Login();
        lo.setVisible(true);
    }//GEN-LAST:event_btn_csActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarLibroActionPerformed
        try {
            EliminarLibro el = new EliminarLibro();
            el.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_eliminarLibroActionPerformed

    private void btn_editarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarLibroActionPerformed
        EditarLibro el = null;
        try {
            el = new EditarLibro();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        el.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_editarLibroActionPerformed

    private void btn_buscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarLibroActionPerformed
        BuscarLibro bl = null;
        try {
            bl = new BuscarLibro();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        bl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_buscarLibroActionPerformed

    private void btn_Menu_IngresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Menu_IngresarLibroActionPerformed
        IngresarLibro il = new IngresarLibro();
        il.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Menu_IngresarLibroActionPerformed

    private void btn_eliminarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarAdminActionPerformed
        try {
            EliminarAdmin ea;
            ea = new EliminarAdmin();
            ea.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_eliminarAdminActionPerformed

    private void btn_editarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarAdminActionPerformed
        try {
            EditarAdministrador ea = new EditarAdministrador();
            ea.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editarAdminActionPerformed

    private void tbn_buscarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_buscarAdminActionPerformed
        try {
            BuscarAdmin ba;
            ba = new BuscarAdmin();
            ba.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbn_buscarAdminActionPerformed

    private void btn_sing_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sing_AdminActionPerformed
        IngresarAdmin am = new IngresarAdmin();
        am.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_sing_AdminActionPerformed

    private void btn_salir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salir3ActionPerformed

    private void btn_cs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cs2ActionPerformed
         this.setVisible(false);
        Login lo = new Login();
        lo.setVisible(true);
    }//GEN-LAST:event_btn_cs2ActionPerformed
    
   
    
    public void CargarTabla(JTable tabla, String cadena) throws SQLException, ClassNotFoundException{
        DefaultTableModel modelo;
        String [] titulo = {"CODIGO", "USUARIO","TIPO USER","PASSWORD"};
        modelo = new DefaultTableModel(null,titulo);
        
        String [] registros = new String[4];
        String sql = "SELECT codigo, usuario, tipouser, password FROM usuarios WHERE CONCAT (codigo, usuario, tipouser, password) LIKE '%"+cadena+"%'";
        Conexion con = new Conexion();  
        cn = (Connection) con.conectar();        
        try{
            Statement st  = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                for (int i = 0; i <4; i++) 
                    registros[i]= rs.getString(i+1);
                modelo.addRow(registros);                
            }
            tabla.setModel(modelo);
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null,"Error: "+ e);
        }
    }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuAdmin().setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_usuarios;
    private javax.swing.JButton btn_Menu_IngresarLibro;
    private javax.swing.JButton btn_buscarEstudiante;
    private javax.swing.JButton btn_buscarLibro;
    private javax.swing.JButton btn_cs;
    private javax.swing.JButton btn_cs1;
    private javax.swing.JButton btn_cs2;
    private javax.swing.JButton btn_editarAdmin;
    private javax.swing.JButton btn_editarEstudiante;
    private javax.swing.JButton btn_editarLibro;
    private javax.swing.JButton btn_eliminarAdmin;
    private javax.swing.JButton btn_eliminarLibro;
    private javax.swing.JButton btn_ingresarEst;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_salir2;
    private javax.swing.JButton btn_salir3;
    private javax.swing.JButton btn_sing_Admin;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel_libros;
    private javax.swing.JButton tbn_buscarAdmin;
    // End of variables declaration//GEN-END:variables
}
