package interfaces;



import com.mysql.jdbc.Connection;
import java.io.Serializable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import coneccion.Conexion;


/**
 *
 * @author danna
 */
public class MenuAdmin extends javax.swing.JFrame implements Serializable{
Connection cn;
private int id;
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() throws SQLException, ClassNotFoundException {
        initComponents();
        cargarTabla("");
        setLocationRelativeTo(null);//Centrar Ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_libros = new javax.swing.JPanel();
        btn_Menu_IngresarLibro = new javax.swing.JButton();
        btn_buscarLibro = new javax.swing.JButton();
        btn_editarLibro = new javax.swing.JButton();
        btn_eliminarLibro = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_cs = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Panel_usuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_sing_Admin = new javax.swing.JButton();
        tbn_buscarAdmin = new javax.swing.JButton();
        btn_editarAdmin = new javax.swing.JButton();
        btn_eliminarAdmin = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Panel_Estudiantes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_ingresarEst = new javax.swing.JButton();
        btn_buscarEstudiante = new javax.swing.JButton();
        btn_editarEstudiante = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btn_salir2 = new javax.swing.JButton();
        btn_cs1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Panel_login = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_buscar = new javax.swing.JTable();
        txt_usuarios_user = new javax.swing.JTextField();
        txt_usuario_tipousuario = new javax.swing.JTextField();
        txt_usuario_pass = new javax.swing.JTextField();
        APELLIDO = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        txt_usuario_codigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        panel_libros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Menu_IngresarLibro.setText("INGRESAR LIBRO");
        btn_Menu_IngresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Menu_IngresarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_Menu_IngresarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 254, -1));

        btn_buscarLibro.setText("BUSCAR LIBRO");
        btn_buscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_buscarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 254, -1));

        btn_editarLibro.setText("EDITAR LIBRO");
        btn_editarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_editarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 254, -1));

        btn_eliminarLibro.setText("ELIMINAR LIBRO");
        btn_eliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarLibroActionPerformed(evt);
            }
        });
        panel_libros.add(btn_eliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 254, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("PANEL DE ADMINISTRACION");
        panel_libros.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_libros.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 408, 125, -1));

        btn_cs.setText("CERRAR SESION");
        btn_cs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_csActionPerformed(evt);
            }
        });
        panel_libros.add(btn_cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 408, 145, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menuUser.jpg"))); // NOI18N
        panel_libros.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 570));

        jTabbedPane1.addTab("Libros", panel_libros);

        Panel_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PANEL DE ADMINISTRACION");
        Panel_usuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 37, -1, 27));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRADOR");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btn_sing_Admin.setBackground(new java.awt.Color(0, 0, 0));
        btn_sing_Admin.setForeground(new java.awt.Color(255, 255, 255));
        btn_sing_Admin.setText("INGRESAR ADMINISTRADOR");
        btn_sing_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sing_AdminActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sing_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        tbn_buscarAdmin.setText("BUSCAR ADMINISTRADOR");
        tbn_buscarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_buscarAdminActionPerformed(evt);
            }
        });
        jPanel3.add(tbn_buscarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 187, -1));

        btn_editarAdmin.setText("EDITAR ADMINISTRADOR");
        btn_editarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btn_editarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 187, -1));

        btn_eliminarAdmin.setText("ELIMINAR ADMINISTRADOR");
        btn_eliminarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btn_eliminarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 187, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/galaxy.jpg"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 310));

        Panel_usuarios.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 300, 310));

        Panel_Estudiantes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Panel_Estudiantes.setToolTipText("");
        Panel_Estudiantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ESTUDIANTES");
        Panel_Estudiantes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btn_ingresarEst.setBackground(new java.awt.Color(0, 0, 0));
        btn_ingresarEst.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresarEst.setText("INGRESAR ESTUDIANTE");
        btn_ingresarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarEstActionPerformed(evt);
            }
        });
        Panel_Estudiantes.add(btn_ingresarEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btn_buscarEstudiante.setText("BUSCAR ESTUDIANTE");
        btn_buscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarEstudianteActionPerformed(evt);
            }
        });
        Panel_Estudiantes.add(btn_buscarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 162, -1));

        btn_editarEstudiante.setText("EDITAR ESTUDIANTE");
        btn_editarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarEstudianteActionPerformed(evt);
            }
        });
        Panel_Estudiantes.add(btn_editarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 162, -1));

        jButton13.setText("ELIMINAR  ESTUDIANTE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Panel_Estudiantes.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 162, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/galaxy.jpg"))); // NOI18N
        Panel_Estudiantes.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 310));

        Panel_usuarios.add(Panel_Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 126, -1, 310));

        btn_salir2.setText("SALIR");
        btn_salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir2ActionPerformed(evt);
            }
        });
        Panel_usuarios.add(btn_salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 510, 131, -1));

        btn_cs1.setText("CERRAR SESION");
        btn_cs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cs1ActionPerformed(evt);
            }
        });
        Panel_usuarios.add(btn_cs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 510, 145, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/books.jpg"))); // NOI18N
        Panel_usuarios.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        jTabbedPane1.addTab("Usuario", Panel_usuarios);

        Panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USUARIOS");
        Panel_login.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INGRESE USUARIOS A BUSCAR");
        Panel_login.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 88, -1, 20));

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        Panel_login.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 84, 319, 30));

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        Panel_login.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 121, -1));

        tabla_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_buscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_buscar);

        Panel_login.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 225, 741, 280));

        txt_usuarios_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarios_userActionPerformed(evt);
            }
        });
        Panel_login.add(txt_usuarios_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 185, 160, 30));
        Panel_login.add(txt_usuario_tipousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 186, 136, 28));
        Panel_login.add(txt_usuario_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 186, 160, 28));

        APELLIDO.setForeground(new java.awt.Color(255, 255, 255));
        APELLIDO.setText("PASSWORD");
        Panel_login.add(APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 153, 80, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TIPO USUARIO");
        Panel_login.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 27));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("USUARIO");
        Panel_login.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, 20));

        btn_modificar.setText("MODIFICAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        Panel_login.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 523, 136, -1));

        btn_atras.setText("ATRAS");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        Panel_login.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 523, 136, -1));

        txt_usuario_codigo.setEditable(false);
        txt_usuario_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usuario_codigoMouseClicked(evt);
            }
        });
        txt_usuario_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuario_codigoActionPerformed(evt);
            }
        });
        Panel_login.add(txt_usuario_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 160, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CODIGO");
        Panel_login.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 153, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/books.jpg"))); // NOI18N
        Panel_login.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        jTabbedPane1.addTab("Login", Panel_login);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuario_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuario_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuario_codigoActionPerformed

    private void txt_usuario_codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuario_codigoMouseClicked
        JOptionPane.showMessageDialog(rootPane, "No Editable");
    }//GEN-LAST:event_txt_usuario_codigoMouseClicked

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        MenuAdmin ma = null;
        try {
            ma = new MenuAdmin();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (id!=0) {
            String codigo = txt_usuario_codigo.getText();
            String user = txt_usuarios_user.getText();
            String tipo = txt_usuario_tipousuario.getText();
            String pass = txt_usuario_pass.getText();
            try {
                if (tipo == "" && pass =="" && codigo =="") {
                    JOptionPane.showMessageDialog(this, "Por Favor Complete Los Campos");
                }else{
                    if (JOptionPane.showConfirmDialog(rootPane, "Editar Registro!, ¿desea continuar?",
                        "Editar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    Statement smt = cn.createStatement();
                    smt.execute("UPDATE usuarios set usuario='"+user+"', tipouser='"+tipo+"', password='"+pass+"' WHERE codigo ="+id);
                    JOptionPane.showMessageDialog(this, "Datos Actualizados Correctamente!");
                    smt.close();
                    cargarTabla("");
                    limpiarcajas();
                    id = 0;
                }else{
                    cargarTabla("");
                    limpiarcajas();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar los datos " +e);
        }
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void txt_usuarios_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarios_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarios_userActionPerformed

    private void tabla_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_buscarMouseClicked
        try {
            id  = Integer.parseInt((String) tabla_buscar.getValueAt(tabla_buscar.getSelectedRow(), 0));
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("SELECT codigo, usuario, tipouser, password FROM usuarios WHERE codigo ="+id);
            if (rs.next()) {
                txt_usuario_codigo.setText(rs.getString(1));
                txt_usuarios_user.setText(rs.getString(2));
                txt_usuario_tipousuario.setText(rs.getString(3));
                txt_usuario_pass.setText(rs.getString(4));
            }
            rs.close();
            smt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tabla_buscarMouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        try {
            cargarTabla("");
            limpiarcajas();
        } catch (SQLException ex) {
            Logger.getLogger(BuscarAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BuscarAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_buscar.setText(null);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        try {
            cargarTabla(txt_buscar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(BuscarAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BuscarAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void btn_cs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cs1ActionPerformed
        this.setVisible(false);
        Login lo = new Login();
        lo.setVisible(true);
    }//GEN-LAST:event_btn_cs1ActionPerformed

    private void btn_salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salir2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            EliminarEstudiante ee = new EliminarEstudiante();
            ee.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void btn_editarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarEstudianteActionPerformed
        try {
            EditarEstudiante es = new EditarEstudiante();
            es.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_editarEstudianteActionPerformed

    private void btn_buscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarEstudianteActionPerformed
        try {
            BuscarEstudiante be = new BuscarEstudiante();
            be.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_buscarEstudianteActionPerformed

    private void btn_ingresarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarEstActionPerformed
        IngresarEstudiante is = new IngresarEstudiante();
        is.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingresarEstActionPerformed

    private void btn_eliminarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarAdminActionPerformed
        try {
            EliminarAdmin ea;
            ea = new EliminarAdmin();
            ea.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_eliminarAdminActionPerformed

    private void btn_editarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarAdminActionPerformed
        try {
            EditarAdministrador ea = new EditarAdministrador();
            ea.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editarAdminActionPerformed

    private void tbn_buscarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_buscarAdminActionPerformed
        try {
            BuscarAdmin ba;
            ba = new BuscarAdmin();
            ba.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbn_buscarAdminActionPerformed

    private void btn_sing_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sing_AdminActionPerformed
        IngresarAdmin am = new IngresarAdmin();
        am.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_sing_AdminActionPerformed

    private void btn_csActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_csActionPerformed
        this.setVisible(false);
        Login lo = new Login();
        lo.setVisible(true);
    }//GEN-LAST:event_btn_csActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarLibroActionPerformed
        try {
            EliminarLibro el = new EliminarLibro();
            el.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_eliminarLibroActionPerformed

    private void btn_editarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarLibroActionPerformed
        EditarLibro el = null;
        try {
            el = new EditarLibro();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        el.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_editarLibroActionPerformed

    private void btn_buscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarLibroActionPerformed
        BuscarLibro bl = null;
        try {
            bl = new BuscarLibro();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        bl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_buscarLibroActionPerformed

    private void btn_Menu_IngresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Menu_IngresarLibroActionPerformed
        IngresarLibro il = new IngresarLibro();
        il.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Menu_IngresarLibroActionPerformed
    
    void cargarTabla(String cad) throws SQLException, ClassNotFoundException{
        CargarTabla(tabla_buscar, cad);
    }
    
    public void CargarTabla(JTable tabla, String cadena) throws SQLException, ClassNotFoundException{
        DefaultTableModel modelo;
        String [] titulo = {"CODIGO", "USUARIO","TIPO USER","PASSWORD"};
        modelo = new DefaultTableModel(null,titulo);
        
        String [] registros = new String[4];
        String sql = "SELECT codigo, usuario, tipouser, password FROM usuarios WHERE CONCAT (codigo, usuario, tipouser, password) LIKE '%"+cadena+"%'";
        Conexion con = new Conexion();  
        cn = (Connection) con.conectar();        
        try{
            Statement st  = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                for (int i = 0; i <4; i++) 
                    registros[i]= rs.getString(i+1);
                modelo.addRow(registros);                
            }
            tabla.setModel(modelo);
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null,"Error: "+ e);
        }
    }
        
    public void limpiarcajas(){
        txt_usuario_codigo.setText("");
        txt_usuarios_user.setText("");
        txt_usuario_tipousuario.setText("");
        txt_usuario_pass.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuAdmin().setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APELLIDO;
    private javax.swing.JPanel Panel_Estudiantes;
    private javax.swing.JPanel Panel_login;
    private javax.swing.JPanel Panel_usuarios;
    private javax.swing.JButton btn_Menu_IngresarLibro;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_buscarEstudiante;
    private javax.swing.JButton btn_buscarLibro;
    private javax.swing.JButton btn_cs;
    private javax.swing.JButton btn_cs1;
    private javax.swing.JButton btn_editarAdmin;
    private javax.swing.JButton btn_editarEstudiante;
    private javax.swing.JButton btn_editarLibro;
    private javax.swing.JButton btn_eliminarAdmin;
    private javax.swing.JButton btn_eliminarLibro;
    private javax.swing.JButton btn_ingresarEst;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_salir2;
    private javax.swing.JButton btn_sing_Admin;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel_libros;
    private javax.swing.JTable tabla_buscar;
    private javax.swing.JButton tbn_buscarAdmin;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_usuario_codigo;
    private javax.swing.JTextField txt_usuario_pass;
    private javax.swing.JTextField txt_usuario_tipousuario;
    private javax.swing.JTextField txt_usuarios_user;
    // End of variables declaration//GEN-END:variables
}
